apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelland-chat
spec:
  selector:
    matchLabels:
      app: pixelland-chat
  template:
    metadata:
      labels:
        app: pixelland-chat
    spec:
      containers:
        - name: pixelland-chat
          image: wwwillw/pixelland-chat
          ports:
            - containerPort: 8081
          env:
            - name: CHAT_PORT
              value: "8081"
            - name: CHAT_DEBUG
              value: "true"
            - name: CHAT_ENFORCE_AUTH
              value: "false"
            - name: CHAT_SQL_HOST
              value: "postgresql.default.svc.cluster.local"
            - name: CHAT_SQL_PORT
              value: "5433"
            - name: CHAT_SQL_USER
              value: "postgres"
            - name: CHAT_SQL_PASSWORD
              value: "zeno_robot"
            - name: CHAT_SQL_DB_NAME
              value: "pixellandchat"
            - name: CHAT_SQL_SSL_MODE
              value: "disable"
            - name: CHAT_SEED_DB
              value: "true"
          volumeMounts:
            - name: credentials
              mountPath: "/etc/credentials"
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: gcp-service-account
            optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: pixelland-chat
spec:
  type: LoadBalancer
  selector:
    app: pixelland-chat
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
